from django.db import models

class Article(models.Model):
    code_article = models.CharField(max_length=255,db_column='Code article', null=True, blank=True)
    article = models.CharField(max_length=255, db_column='ARTICLE', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    fournisseur = models.CharField(max_length=255, db_column='FOURNISSEUR', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    secteur = models.CharField(max_length=255, db_column='SECTEUR', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)

class EconomicsSMG(models.Model):
    code_article = models.CharField(max_length=255, db_column='Code article', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    cout_dpr = models.FloatField(db_column='Coût DPR', null=True, blank=True)
    qte = models.IntegerField(db_column='QTE', null=True, blank=True)
    pro_qte = models.IntegerField(db_column='PRO QTE', null=True, blank=True)
    ca_ttc = models.FloatField(db_column='CA TTC', null=True, blank=True)
    pro_ca_ttc = models.FloatField(db_column='PRO CA TTC', null=True, blank=True)
    nombre_darticles = models.IntegerField(db_column="Nombre d'articles", null=True, blank=True)
    frequentation = models.IntegerField(db_column='FREQUENTATION', null=True, blank=True)
    liste_de_guerre_course = models.CharField(max_length=255, db_column='Liste de guerre / course', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)

class PrixP1(models.Model):
    code_article = models.CharField(max_length=255, db_column='Code article', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    prix_p1 = models.FloatField(db_column='Prix P1', null=True, blank=True)
    prix_p1_ca_ttc = models.FloatField(db_column='Prix P1 - CA TTC', null=True, blank=True)
    prix_p1_marge = models.FloatField(db_column='Prix P1 - MArge', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)

class PrixP3(models.Model):
    code_article = models.CharField(max_length=255, db_column='Code article', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    prix_p3 = models.FloatField(db_column='Prix P3', null=True, blank=True)
    prix_p3_ref_couverte = models.IntegerField(db_column='Prix P3 - Ref couverte', null=True, blank=True)
    prix_p3_ca_ttc_ref = models.FloatField(db_column='Prix P3 - CA TTC Ref', null=True, blank=True)
    prix_p3_ca_ttc = models.FloatField(db_column='Prix P3 - CA TTC', null=True, blank=True)
    prix_p3_indice_prix = models.FloatField(db_column='Prix P3 - Indice prix', null=True, blank=True)
    prix_p3_indice_prix_bucket = models.CharField(max_length=255, db_column='Prix P3 - Indice prix (bucket)', null=True, blank=True)
    prix_p3_marge = models.FloatField(db_column='Prix P3 - Marge', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)

class PrixMoyenHorsPromo(models.Model):
    code_article = models.CharField(max_length=255, db_column='Code article', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    prix_moyen_hors_promo = models.FloatField(db_column='Prix moyen hors promo', null=True, blank=True)
    prix_moyen_hors_promo_ref_couverte = models.IntegerField(db_column='Prix moyen hors promo - ref couverte', null=True, blank=True)
    prix_moyen_hors_promo_ca_ttc_ref = models.FloatField(db_column='Prix moyen hors promo - CA TTC Ref', null=True, blank=True)
    prix_moyen_hors_promo_ca_ttc = models.FloatField(db_column='Prix moyen hors promo - CA TTC', null=True, blank=True)
    prix_moyen_hors_promo_indice_prix = models.FloatField(db_column='Prix moyen hors promo - Indice prix', null=True, blank=True)
    prix_moyen_hors_promo_indice_prix_bucket = models.CharField(max_length=255, db_column='Prix moyen hors promo - Indice prix (bucket)', null=True, blank=True)
    prix_moyen_hors_promo_marge = models.FloatField(db_column='Prix moyen hors promo - Marge', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)

class PrixCible(models.Model):
    code_article = models.CharField(max_length=255, db_column='Code article', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    prix_cible = models.FloatField(db_column='Prix cible', null=True, blank=True)
    prix_cible_ref_couverte = models.IntegerField(db_column='Prix cible - Ref couverte', null=True, blank=True)
    prix_cible_ca_ttc_ref = models.FloatField(db_column='Prix cible - CA TTC Ref', null=True, blank=True)
    prix_cible_ca_ttc = models.FloatField(db_column='Prix cible - CA TTC', null=True, blank=True)
    prix_cible_indice_prix = models.FloatField(db_column='Prix cible - Indice prix', null=True, blank=True)
    prix_cible_indice_prix_bucket = models.CharField(max_length=255, db_column='Prix cible - Indice prix (bucket)', null=True, blank=True)
    prix_cible_marge = models.FloatField(db_column='Prix cible - Marge', null=True, blank=True)
    prix_cible_percent_impact_vol = models.FloatField(db_column='Prix cible - % impact vol', null=True, blank=True)
    prix_cible_percent_impact_ca = models.FloatField(db_column='Prix cible - % impact CA %', null=True, blank=True)
    prix_cible_percent_impact_marge = models.FloatField(db_column='Prix cible - % impact marge', null=True, blank=True)
    prix_cible_impact_ca = models.FloatField(db_column='Prix cible - impact CA', null=True, blank=True)
    prix_cible_impact_marge = models.FloatField(db_column='Prix cible - impact marge', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)

class ConcurrentsLeMoinsCher(models.Model):
    code_article = models.CharField(max_length=255, db_column='Code article', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    prix_min = models.FloatField(db_column='Prix Min', null=True, blank=True)
    concurrent = models.CharField(max_length=255, db_column='Concurrent', null=True, blank=True)
    prix_min_ref_couverte = models.IntegerField(db_column='Prix Min - Ref couverte', null=True, blank=True)
    prix_min_ca_ttc_ref = models.IntegerField(db_column='Prix Min - CA TTC Ref', null=True, blank=True)
    prix_min_ca_ttc = models.IntegerField(db_column='Prix Min - CA TTC', null=True, blank=True)
    prix_min_indice_prix = models.FloatField(db_column='Prix Min - Indice prix', null=True, blank=True)
    prix_min_indice_prix_bucket = models.CharField(max_length=255, db_column='Prix Min - Indice prix (bucket)', null=True, blank=True)
    prix_min_marge = models.FloatField(db_column='Prix Min - Marge', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)

class CarrefourMarket(models.Model):
    code_article = models.CharField(max_length=255, db_column='code_article', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    carrefour_market_prix = models.FloatField(db_column='carrefour_market_prix', null=True, blank=True)
    carrefour_market_date_de_releve = models.DateTimeField(db_column='carrefour_market_date_de_releve', null=True, blank=True)
    carrefour_market_id_releve = models.CharField(max_length=255, db_column='carrefour_market_id_releve', null=True, blank=True)
    carrefour_market_prix_manuel = models.FloatField(db_column='carrefour_market_prix_manuel', null=True, blank=True)
    carrefour_market_ref_couverture = models.IntegerField(db_column='carrefour_market_ref_couverture', null=True, blank=True)
    carrefour_market_ca_ttc_ref = models.IntegerField(db_column='carrefour_market_ca_ttc_ref', null=True, blank=True)
    carrefour_market_ca_ttc = models.IntegerField(db_column='carrefour_market_ca_ttc', null=True, blank=True)
    carrefour_market_indice_prix = models.FloatField(db_column='carrefour_market_indice_prix', null=True, blank=True)
    carrefour_market_indice_prix_bucket = models.CharField(max_length=255, db_column='carrefour_market_indice_prix_bucket', null=True, blank=True)
    carrefour_market_marge = models.FloatField(db_column='carrefour_market_marge', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)

class CarrefourHyper(models.Model):
    code_article = models.CharField(max_length=255,db_column='Code article', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    carrefour_hyper_prix = models.FloatField(db_column='Carrefour Hyper Prix', null=True, blank=True)
    carrefour_hyper_date_de_releve = models.DateTimeField(db_column='Carrefour Hyper Date de relevé', null=True, blank=True)
    carrefour_hyper_id_releve = models.FloatField(db_column='Carrefour Hyper - ID Relevé', null=True, blank=True)
    carrefour_hyper_prix_manuel = models.CharField(max_length=255, db_column='Carrefour Hyper - Prix manuel', null=True, blank=True)
    carrefour_hyper_ref_couverte = models.IntegerField(db_column='Carrefour Hyper - Ref couverte', null=True, blank=True)
    carrefour_hyper_ca_ttc_ref = models.IntegerField(db_column='Carrefour Hyper - CA TTC Ref', null=True, blank=True)
    carrefour_hyper_ca_ttc = models.IntegerField(db_column='Carrefour Hyper - CA TTC', null=True, blank=True)
    carrefour_hyper_indice_prix = models.FloatField(db_column='Carrefour Hyper - Indice prix', null=True, blank=True)
    carrefour_hyper_indice_prix_bucket = models.CharField(max_length=255, db_column='Carrefour Hyper - Indice prix (bucket)', null=True, blank=True)
    carrefour_hyper_marge = models.FloatField(db_column='Carrefour Hyper - Marge', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)

class Monoprix(models.Model):
    code_article = models.CharField(max_length=255, db_column='Code article', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    monoprix_prix = models.FloatField(db_column='Monoprix Prix', null=True, blank=True)
    monoprix_date_de_releve = models.DateTimeField(db_column='Monoprix Date de relevé', null=True, blank=True)
    monoprix_id_releve = models.FloatField(db_column='Monoprix - ID Relevé', null=True, blank=True)
    monoprix_prix_manuel = models.FloatField(db_column='Monoprix - Prix manuel', null=True, blank=True)
    monoprix_ref_couverte = models.IntegerField(db_column='Monoprix - Ref couverte', null=True, blank=True)
    monoprix_ca_ttc_ref = models.FloatField(db_column='Monoprix - CA TTC Ref', null=True, blank=True)
    monoprix_ca_ttc = models.FloatField(db_column='Monoprix - CA TTC', null=True, blank=True)
    monoprix_indice_prix = models.FloatField(db_column='Monoprix - Indice prix', null=True, blank=True)
    monoprix_indice_prix_bucket = models.CharField(max_length=255, db_column='Monoprix - Indice prix (bucket)', null=True, blank=True)
    monoprix_marge = models.FloatField(db_column='Monoprix - Marge', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)


class Aziza(models.Model):
    code_article = models.CharField(max_length=255,db_column='Code article', null=True, blank=True)
    categorie = models.CharField(max_length=255, db_column='CATEGORIE', null=True, blank=True)
    rayon = models.CharField(max_length=255, db_column='RAYON', null=True, blank=True)
    mdd = models.CharField(max_length=255, db_column='MDD', null=True, blank=True)
    liste_guerre_course = models.CharField(max_length=255, db_column='LISTE DE GUERRE/LISTE DE COURSE', null=True, blank=True)
    aziza_prix = models.FloatField(db_column='Aziza Prix', null=True, blank=True)
    aziza_date_de_releve = models.DateTimeField(db_column='Aziza Date de relevé', null=True, blank=True)
    aziza_id_releve = models.FloatField(db_column='Aziza - ID Relevé', null=True, blank=True)
    aziza_prix_manuel = models.CharField(max_length=255, db_column='Aziza - Prix manuel', null=True, blank=True)
    aziza_ref_couverte = models.IntegerField(db_column='Aziza - Ref couverte', null=True, blank=True)
    aziza_ca_ttc_ref = models.IntegerField(db_column='Aziza - CA TTC Ref', null=True, blank=True)
    aziza_ca_ttc = models.IntegerField(db_column='Aziza - CA TTC', null=True, blank=True)
    aziza_indice_prix = models.FloatField(db_column='Aziza - Indice prix', null=True, blank=True)
    aziza_indice_prix_bucket = models.CharField(max_length=255, db_column='Aziza - Indice prix (bucket)', null=True, blank=True)
    aziza_marge = models.FloatField(db_column='Aziza - Marge', null=True, blank=True)
    etat = models.CharField(max_length=255, db_column='ETAT', null=True, blank=True)
    bucket_de_ca = models.CharField(max_length=255, db_column='Bucket de CA', null=True, blank=True)
    homologation = models.CharField(max_length=255, db_column='Homologation', null=True, blank=True)



