# Generated by Django 5.0.8 on 2024-08-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LIB', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FK_JOUR', models.DateTimeField()),
                ('QT', models.IntegerField()),
                ('LIB', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDeCaisse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NUM_TICKET', models.IntegerField()),
                ('HEURE_VENTE', models.DateTimeField()),
                ('FK_ARTICLE', models.JSONField()),
                ('LIB_LIST', models.JSONField()),
            ],
        ),
    ]
