# Generated by Django 5.0.8 on 2024-09-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affinitytesting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsDeCaisse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('HEURE_VENTE', models.DateTimeField(blank=True, null=True)),
                ('LIB', models.CharField(max_length=255)),
                ('CODE_MAGASIN', models.IntegerField(blank=True, null=True)),
                ('NUM_TICKET', models.IntegerField(blank=True, null=True)),
                ('NUM_TPV', models.IntegerField(blank=True, null=True)),
                ('FK_ARTICLE', models.JSONField(blank=True, null=True)),
                ('QTE', models.FloatField(blank=True, null=True)),
                ('CA_TTC', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mixingtickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM_TICKET', models.IntegerField()),
                ('HEURE_VENTE', models.DateTimeField()),
                ('FK_ARTICLE', models.JSONField()),
                ('Lib_list', models.JSONField()),
                ('CA_LIST', models.JSONField()),
                ('QT_LIST', models.JSONField()),
            ],
        ),        
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_article', models.IntegerField(null=True, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('lib', models.CharField(max_length=255)),
                ('lib_commercial', models.CharField(max_length=255)),
                ('ean', models.CharField(blank=True, max_length=13, null=True)),
                ('unite_mesure', models.CharField(max_length=50)),
                ('code_ray', models.CharField(max_length=50)),
                ('rayon', models.CharField(max_length=100)),
                ('code_marche', models.CharField(max_length=50)),
                ('marche', models.CharField(max_length=100)),
                ('code_famille', models.CharField(max_length=50)),
                ('famille', models.CharField(max_length=100)),
                ('sous_famille', models.CharField(blank=True, max_length=100, null=True)),
                ('code_sfa', models.CharField(blank=True, max_length=50, null=True)),
                ('code_depart', models.CharField(max_length=50)),
                ('departement', models.CharField(max_length=100)),
                ('ubs', models.CharField(blank=True, max_length=50, null=True)),
                ('code_ubs', models.CharField(blank=True, max_length=50, null=True)),
                ('code_segment', models.CharField(max_length=50)),
                ('segment', models.CharField(max_length=100)),
                ('mode_appro', models.CharField(max_length=50)),
                ('groupe', models.CharField(blank=True, max_length=100, null=True)),
                ('commandable', models.BooleanField(default=True)),
                ('lib_mdd', models.CharField(blank=True, max_length=100, null=True)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_marque', models.CharField(blank=True, max_length=50, null=True)),
                ('type_marque', models.CharField(blank=True, max_length=50, null=True)),
                ('etat', models.CharField(max_length=50)),
            ],
        ),
    ]
