# Generated by Django 4.1.13 on 2024-08-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aziza',
            name='bucket_de_ca',
            field=models.CharField(blank=True, db_column='Bucket de CA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aziza',
            name='homologation',
            field=models.CharField(blank=True, db_column='Homologation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrefourhyper',
            name='bucket_de_ca',
            field=models.CharField(blank=True, db_column='Bucket de CA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrefourhyper',
            name='homologation',
            field=models.CharField(blank=True, db_column='Homologation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrefourmarket',
            name='bucket_de_ca',
            field=models.CharField(blank=True, db_column='Bucket de CA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrefourmarket',
            name='homologation',
            field=models.CharField(blank=True, db_column='Homologation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concurrentslemoinscher',
            name='bucket_de_ca',
            field=models.CharField(blank=True, db_column='Bucket de CA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concurrentslemoinscher',
            name='homologation',
            field=models.CharField(blank=True, db_column='Homologation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monoprix',
            name='bucket_de_ca',
            field=models.CharField(blank=True, db_column='Bucket de CA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monoprix',
            name='homologation',
            field=models.CharField(blank=True, db_column='Homologation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixcible',
            name='bucket_de_ca',
            field=models.CharField(blank=True, db_column='Bucket de CA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixcible',
            name='homologation',
            field=models.CharField(blank=True, db_column='Homologation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixmoyenhorspromo',
            name='bucket_de_ca',
            field=models.CharField(blank=True, db_column='Bucket de CA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixmoyenhorspromo',
            name='homologation',
            field=models.CharField(blank=True, db_column='Homologation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixp1',
            name='bucket_de_ca',
            field=models.CharField(blank=True, db_column='Bucket de CA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixp1',
            name='homologation',
            field=models.CharField(blank=True, db_column='Homologation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixp3',
            name='bucket_de_ca',
            field=models.CharField(blank=True, db_column='Bucket de CA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixp3',
            name='homologation',
            field=models.CharField(blank=True, db_column='Homologation', max_length=255, null=True),
        ),
    ]
