# Generated by Django 4.1.13 on 2024-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0002_aziza_bucket_de_ca_aziza_homologation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aziza',
            name='rayon',
            field=models.CharField(blank=True, db_column='RAYON', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrefourhyper',
            name='rayon',
            field=models.CharField(blank=True, db_column='RAYON', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrefourmarket',
            name='rayon',
            field=models.CharField(blank=True, db_column='RAYON', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concurrentslemoinscher',
            name='rayon',
            field=models.CharField(blank=True, db_column='RAYON', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='economicssmg',
            name='rayon',
            field=models.CharField(blank=True, db_column='RAYON', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monoprix',
            name='rayon',
            field=models.CharField(blank=True, db_column='RAYON', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixcible',
            name='rayon',
            field=models.CharField(blank=True, db_column='RAYON', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixmoyenhorspromo',
            name='rayon',
            field=models.CharField(blank=True, db_column='RAYON', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixp1',
            name='rayon',
            field=models.CharField(blank=True, db_column='RAYON', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixp3',
            name='rayon',
            field=models.CharField(blank=True, db_column='RAYON', max_length=255, null=True),
        ),
    ]
