# Generated by Django 4.1.13 on 2024-08-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0003_aziza_rayon_carrefourhyper_rayon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bucket_de_ca',
        ),
        migrations.RemoveField(
            model_name='article',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='article',
            name='homologation',
        ),
        migrations.RemoveField(
            model_name='article',
            name='secteur',
        ),
        migrations.AddField(
            model_name='article',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
    ]
