# Generated by Django 4.1.13 on 2024-08-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0004_remove_article_bucket_de_ca_remove_article_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bucket_de_ca',
            field=models.CharField(blank=True, db_column='Bucket de CA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='homologation',
            field=models.CharField(blank=True, db_column='Homologation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='secteur',
            field=models.CharField(blank=True, db_column='SECTEUR', max_length=255, null=True),
        ),
    ]
