# Generated by Django 4.1.13 on 2024-08-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0005_article_bucket_de_ca_article_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aziza',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aziza',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrefourhyper',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrefourhyper',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrefourmarket',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carrefourmarket',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concurrentslemoinscher',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concurrentslemoinscher',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='economicssmg',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='economicssmg',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monoprix',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monoprix',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixcible',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixcible',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixmoyenhorspromo',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixmoyenhorspromo',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixp1',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixp1',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixp3',
            name='etat',
            field=models.CharField(blank=True, db_column='ETAT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prixp3',
            name='liste_guerre_course',
            field=models.CharField(blank=True, db_column='LISTE DE GUERRE/LISTE DE COURSE', max_length=255, null=True),
        ),
    ]
