# Generated by Django 5.0.8 on 2024-10-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_index', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('end', models.CharField(max_length=50)),
                ('log_id', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('object_confidence', models.FloatField()),
                ('object_id', models.IntegerField()),
                ('object_type', models.CharField(max_length=50)),
                ('place_name', models.CharField(max_length=255)),
                ('sensor_description', models.CharField(max_length=255)),
                ('sensor_id', models.CharField(max_length=255)),
                ('smooth_locations_type', models.CharField(max_length=50)),
                ('smooth_locations_coordinates', models.JSONField()),
                ('speed', models.FloatField()),
                ('timestamp', models.CharField(max_length=50)),
                ('cell_numbers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('object_id', models.IntegerField()),
                ('object_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('sensor_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SmoothLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(max_length=50)),
                ('coordinates', models.JSONField()),
            ],
        ),
    ]
