# Generated by Django 5.0.8 on 2024-10-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_behavior', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorMDX',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_id', models.CharField(blank=True, max_length=255, null=True)),
                ('_index', models.CharField(blank=True, max_length=255, null=True)),
                ('_score', models.FloatField(blank=True, null=True)),
                ('_type', models.CharField(blank=True, max_length=255, null=True)),
                ('analytics_module_description', models.CharField(blank=True, max_length=255, null=True)),
                ('analytics_module_id', models.CharField(blank=True, max_length=255, null=True)),
                ('analytics_module_source', models.CharField(blank=True, max_length=255, null=True)),
                ('analytics_module_version', models.CharField(blank=True, max_length=255, null=True)),
                ('bearing', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('edges', models.CharField(blank=True, max_length=255, null=True)),
                ('end', models.CharField(blank=True, max_length=255, null=True)),
                ('gazes', models.TextField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('lip_activities', models.TextField(blank=True, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
                ('object_bbox_bottomY', models.FloatField(blank=True, null=True)),
                ('object_bbox_leftX', models.FloatField(blank=True, null=True)),
                ('object_bbox_rightX', models.FloatField(blank=True, null=True)),
                ('object_bbox_topY', models.FloatField(blank=True, null=True)),
                ('object_confidence', models.FloatField(blank=True, null=True)),
                ('object_coordinate_x', models.FloatField(blank=True, null=True)),
                ('object_coordinate_y', models.FloatField(blank=True, null=True)),
                ('object_coordinate_z', models.FloatField(blank=True, null=True)),
                ('object_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_location_alt', models.FloatField(blank=True, null=True)),
                ('object_location_lat', models.FloatField(blank=True, null=True)),
                ('object_location_lon', models.FloatField(blank=True, null=True)),
                ('object_speed', models.FloatField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('place_name', models.CharField(blank=True, max_length=255, null=True)),
                ('place_type', models.CharField(blank=True, max_length=255, null=True)),
                ('poses', models.TextField(blank=True, null=True)),
                ('sensor_description', models.CharField(blank=True, max_length=255, null=True)),
                ('sensor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sensor_type', models.CharField(blank=True, max_length=255, null=True)),
                ('smooth_locations', models.TextField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('speed_over_time', models.TextField(blank=True, null=True)),
                ('time_interval', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('video_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MTMCMDX',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_id', models.CharField(blank=True, max_length=255, null=True)),
                ('_index', models.CharField(blank=True, max_length=255, null=True)),
                ('_score', models.FloatField(blank=True, null=True)),
                ('_type', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('end', models.CharField(blank=True, max_length=255, null=True)),
                ('global_id', models.CharField(blank=True, max_length=255, null=True)),
                ('matched', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
