# Generated by Django 5.0.8 on 2024-10-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_behavior', '0002_behaviormdx_mtmcmdx'),
    ]

    operations = [
        migrations.CreateModel(
            name='uniquePeople',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('index', models.CharField(max_length=255)),
                ('log_type', models.CharField(max_length=50)),
                ('batch_id', models.IntegerField()),
                ('end', models.DateTimeField()),
                ('global_id', models.IntegerField()),
                ('object_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('matched', models.JSONField()),
            ],
            options={
                'db_table': 'log_entries',
            },
        ),
    ]
